name: Translate strings.xml to French

on:
  pull_request:
    branches:
      - main
    paths:
      - 'android/app/src/main/res/values/strings.xml'

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true 

    - name: List all files after checkout
      run: ls -R

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install googletrans==4.0.0-rc1 

    - name: Translate strings.xml
      run: |
        python scripts/translate_strings.py

    - name: Check if strings_fr.xml was created
      run: ls -R android/app/src/main/res/values-fr

    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Actions"
        git add android/app/src/main/res/values-fr/strings_fr.xml
        git commit -m "Add French translation for strings.xml"
        git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.head_ref }}
